jobs:
  build:
    docker:
    - image: docker:19.03.5
    steps:
    - checkout
    - setup_remote_docker:
        version: 18.09.3
  tests:
    docker:
    - image: jaredallard/triton-base
    steps:
    - checkout
    - restore_cache:
        key: yarn-{{ checksum "package.json" }}
    - run:
        command: yarn --frozen-lockfile
        name: Fetch Dependencies
    - save_cache:
        key: yarn-{{ checksum "package.json" }}
        paths:
        - node_modules
    - run:
        command: yarn test
        name: Run Tests
version: 2
workflows:
  build-push:
    jobs:
    - tests:
        context: Docker
    - build:
        context: Docker
        requires:
        - tests
  version: 2
